name:                haskell-in-depth-exercises
version:             0.1.0.0
github:              "jeremy-miller/haskell-in-depth-exercises"
license:             MIT
author:              "Jeremy Miller"
maintainer:          "jgmiller88@gmail.com"
copyright:           "2019 Jeremy Miller"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jeremy-miller/haskell-in-depth-exercises#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Wredundant-constraints
- -Wnoncanonical-monad-instances

data-files:
- data/*.*

executables:
  # chapter 3
  stockquotes:
    source-dirs: stockquotes
    main: Main.hs
    other-extensions:
    - RecordWildCards
    - OverloadedStrings
    - FlexibleInstances
    - DeriveGeneric
    - DeriveAnyClass
    dependencies:
    - bytestring
    - optparse-applicative
    - time
    - text
    - fmt
    - safe
    - Chart
    - Chart-diagrams
    - cassava
    - blaze-html
